### PR TITLE
feature: skipped signalfd and eventfd when mocking.

### PR DESCRIPTION
**Pull request by spacewander**

### CODE REVIEW

**Comment by spacewander** [comment]
The tests failed in OS X CI environment seems to be the problem of dependency. I rerun the CI with code in the master branch and it also failed: https://travis-ci.org/spacewander/mockeagain/builds/383578164

**Comment by agentzh** [comment]
@spacewander Then we should disable the osx env on traivs?

**Comment by agentzh** [comment]
@spacewander OK, I can reproduce it on my OS X system too:

```
$ make test
export LD_PRELOAD=/Users/agentzh/git/mockeagain/mockeagain.so DYLD_INSERT_LIBRARIES=/Users/agentzh/git/mockeagain/mockeagain.so DYLD_FORCE_FLAT_NAMESPACE=1 MOCKEAGAIN_VERBOSE=1; \
	for t in t/000-mock-writes.c t/001-mock-reads.c t/002-pattern-matching.c t/003-disabled.c; do \
		cc -O -g -Wall -Werror -o ./t/runner $t ./t/runner.c ./t/test_case.c \
		|| exit 1; \
		python ./t/echo_server.py ./t/runner 0 \
		&& echo "Test case $t passed" || exit 1; \
	done
Listening on IP 127.0.0.1 and port 53516
Assertion failed: (n == 1), function run_test, file t/000-mock-writes.c, line 24.
make: *** [test] Error 1
```

This was introduced by the following commit by @dndx:

```
commit 20cd9c4d9af3bd764519b9bf5f973a7183c13608
Author: Datong Sun <dndx@idndx.com>
Date:   Thu Nov 17 04:11:06 2016 -0600

    tests: implemented testing framework and basic tests for mockeagain.

    also added Travis CI for tests.

    Signed-off-by: Yichun Zhang (agentzh) <agentzh@gmail.com>
```

@dndx Will you fix the tests please?

**Comment by agentzh** [comment]
@spacewander Merged. thanks.

**Pull request closed without merging**
